feat: Use starting inventory component instead of a system
Terasology/CoreSampleGameplay pull request #2
Opened 2020-05-22 11:06 UTC by skaldarnar

2020-05-27 08:41 UTC, jdrueckert requested changes

2020-05-27 08:41 UTC, jdrueckert commented on deltas/engine/prefabs/player.prefab
> +      { "uri": "CoreSampleGameplay:companion", "quantity": 99 },
remove

2020-05-27 08:41 UTC, jdrueckert commented on deltas/engine/prefabs/player.prefab
> +}
newline

2020-05-28 08:37 UTC, skaldarnar commented
The latest changes to how the StartingInventory is working in [Terasology/Inventory#13](https://github.com/Terasology/Inventory/pull/13) broke the nested chests by requiring them to have an `InventoryComponent`.

This issue is tracked in https://github.com/Terasology/Inventory/issues/16.

2020-05-30 16:55 UTC, jdrueckert approved these changes

2020-05-30 16:55 UTC, merged